# Introduction to Python
# Module 4 - Handling Numbers with NumPy

Instructor: Suyong Song 

## Exercises for Arrays Creation

Import the <b>numpy</b> package as `np`. 

In [13]:
# Your answer here
import numpy as np

1\. Create an array of length 100 filled with all integer zeros.

In [2]:
# Your answer here
np.zeros(100, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

2\. Create a 10 x 10 array filled with all float ones.

In [3]:
# Your answer here
np.ones((10, 10), dtype = float)

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

3\. Create a 10 x 10 array filled with all integer -1's.

In [5]:
# Your answer here
np.full((10,10),-1, dtype = int)

array([[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]])

4\. Create an array of all two-digit integers (i.e., 10, 11, ..., 99). 

In [7]:
# Your answer here
np.arange(10, 100)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

5\. Create an array of integers from -100 (inclusive) to 100 (inclusive) stepping by 10 (i.e., -100, -90, ..., 100). 

In [8]:
# Your answer here
np.arange(-100,101, 10)

array([-100,  -90,  -80,  -70,  -60,  -50,  -40,  -30,  -20,  -10,    0,
         10,   20,   30,   40,   50,   60,   70,   80,   90,  100])

6\. Create an array of 10 evenly spaced numbers from -100 (inclusive) to 100 (inclusive).

In [9]:
# Your answer here
np.linspace(-100, 100, 10)

array([-100.        ,  -77.77777778,  -55.55555556,  -33.33333333,
        -11.11111111,   11.11111111,   33.33333333,   55.55555556,
         77.77777778,  100.        ])

7\. Create a 10 x 10 square array with integer 1's on the main diagonal and integer 0's elsewhere.

In [10]:
# Your answer here
np.identity(10, dtype=int)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

8\. Set the random seed to 2022 and then create a 5 x 5 array of random numbers that follow a normal distribution with 70 being the mean and 4 being the standard deviation. 

In [21]:
# Your answer here
np.random.seed(2022)
np.random.normal(70,4, (5, 5))

array([[66.61609745, 70.09864648, 66.48923101, 70.80603499, 69.85542042],
       [77.96969387, 70.13860378, 65.89358694, 70.2825359 , 70.0433924 ],
       [69.31151421, 75.37835469, 69.62363993, 65.63677876, 64.03686942],
       [71.16383089, 71.95726404, 72.30835821, 75.61889697, 69.3357309 ],
       [63.38500094, 68.44048497, 76.39003741, 68.24102468, 69.41786185]])

9\. Set the random seed to 2022 and then create an array of 100 random numbers that follow a binomial distribution with 10 trials and 0.5 probability of success. Refer to this document (https://docs.scipy.org/doc/numpy-1.16.1/reference/generated/numpy.random.binomial.html) for the usage of the <b>random.binomial</b> function. 

In [22]:
# Your answer here
np.random.seed(2022)
np.random.binomial(10,0.5, 100)

array([5, 3, 5, 3, 6, 5, 3, 5, 5, 9, 6, 5, 3, 5, 5, 4, 7, 6, 5, 6, 5, 4,
       5, 6, 7, 5, 3, 2, 5, 5, 7, 4, 3, 5, 2, 3, 4, 4, 5, 2, 5, 9, 7, 4,
       4, 6, 5, 5, 3, 1, 4, 5, 6, 7, 5, 6, 3, 5, 4, 3, 6, 6, 4, 6, 7, 6,
       3, 4, 6, 5, 5, 4, 2, 8, 4, 5, 5, 7, 6, 8, 4, 5, 5, 4, 3, 6, 3, 6,
       6, 7, 8, 7, 5, 5, 6, 5, 6, 5, 5, 7])

10\. Set the random seed to 2022 and then create a 10 x 10 array of three-digit random integers.

In [31]:
# Your answer here
np.random.seed(2022)
np.random.randint(100, 1000, (10,10)) 

array([[567, 397, 532, 777, 256, 595, 688, 796, 864, 928],
       [850, 303, 614, 347, 565, 845, 791, 295, 859, 614],
       [645, 822, 907, 763, 771, 584, 485, 780, 511, 655],
       [923, 959, 772, 895, 977, 739, 899, 144, 306, 699],
       [109, 757, 869, 922, 799, 771, 450, 433, 312, 493],
       [718, 521, 295, 583, 946, 272, 275, 122, 937, 533],
       [138, 138, 414, 925, 784, 849, 272, 354, 633, 916],
       [133, 854, 240, 972, 556, 340, 698, 989, 691, 623],
       [352, 859, 209, 715, 380, 964, 482, 405, 600, 582],
       [901, 406, 386, 781, 543, 941, 243, 264, 386, 174]])

11\. Set the random seed to 2022 and then create an array of 10 random integers from 1 (inclusive) to 100 (inclusive) without replacement.

In [16]:
# Your answer here
np.random.seed(2022)
np.random.randint(1, 101, 10) 

array([93, 46, 50, 56, 89, 19, 25, 17, 54, 42])

12\. Set the random seed to 2022 and then create a permuted array of integers from 1 (inclusive) to 100 (inclusive).

In [27]:
# Your answer here
np.random.seed(2202)
np.random.permutation(np.arange(1, 101))

array([ 20,  94,  69,  35,  96,  87,  64,   8,  37,  30, 100,  14,   7,
        27,  26,  51,  99,  89,   1,  58,  93,  54,  70,  78,  17,  11,
         5,  59,  62,  74,  66,  63,  31,  75,  25,  12,  95,  16,  53,
         9,  80,  13,  86,  22,  47,  46,  88,  65,  39,  50,   6,  92,
        23,  48,  72,  15,  36,   4,  97,  85,  19,  43,  71,  21,  98,
        73,  60,  55,  81,  18,  10,  45,  90,  79,  33,  67,  56,  44,
        28,  41,   2,  32,  24,  40,  83,  34,  91,  68,  52,  82,   3,
        76,  61,  57,  77,  29,  38,  49,  42,  84])

## Exercises for Array Indexing and Slicing

In [4]:
np.random.seed(seed=0)
x = np.random.randint(1, 101, 10)
x

array([45, 48, 65, 68, 68, 10, 84, 22, 37, 88])

1\. Select the first 5 values from `x`.

In [12]:
# Your answer here
x[:5]

array([45, 48, 65, 68, 68])

2\. Select the last 5 values from `x`. 

In [14]:
# Your answer here
x[-5:]

array([10, 84, 22, 37, 88])

3\. Select the values from `x` starting with the first value and stepping by 3.

In [15]:
# Your answer here
x[::3]

array([45, 68, 84, 88])

4\. Get the reverse of `x`. 

In [16]:
# Your answer here
x[::-1]

array([88, 37, 22, 84, 10, 68, 68, 65, 48, 45])

<hr>

In [5]:
np.random.seed(seed=0)
y = np.random.randint(100, 1000, (10, 10))
y

array([[784, 659, 729, 292, 935, 863, 807, 459, 109, 823],
       [377, 854, 904, 699, 170, 572, 700, 496, 414, 805],
       [586, 651, 187, 274, 700, 949, 777, 637, 945, 172],
       [877, 215, 855, 809, 947, 531, 548, 950, 199, 277],
       [855, 897, 759, 247, 523, 388, 365, 797, 739, 644],
       [643, 814, 344, 251, 775, 610, 559, 982, 283, 128],
       [902, 228, 228, 153, 650, 588, 856, 373, 435, 488],
       [717, 142, 542, 643, 988, 357, 421, 157, 391, 970],
       [219, 879, 530, 182, 191, 996, 498, 711, 665, 733],
       [184, 303, 424, 874, 147, 739, 231, 968, 280, 946]])

5\. Get the shape of `y`.

In [6]:
# Your answer here
y.shape

(10, 10)

6\. Get the number of all values in `y`.

In [20]:
# Your answer here
y.size

100

7\. Select the first 5 rows from `y`. 

In [8]:
# Your answer here
y[:5,]

array([[784, 659, 729, 292, 935, 863, 807, 459, 109, 823],
       [377, 854, 904, 699, 170, 572, 700, 496, 414, 805],
       [586, 651, 187, 274, 700, 949, 777, 637, 945, 172],
       [877, 215, 855, 809, 947, 531, 548, 950, 199, 277],
       [855, 897, 759, 247, 523, 388, 365, 797, 739, 644]])

8\. Select the first 5 columns from `y`.

In [14]:
# Your answer here
y[:,:5]

array([[784, 659, 729, 292, 935],
       [377, 854, 904, 699, 170],
       [586, 651, 187, 274, 700],
       [877, 215, 855, 809, 947],
       [855, 897, 759, 247, 523],
       [643, 814, 344, 251, 775],
       [902, 228, 228, 153, 650],
       [717, 142, 542, 643, 988],
       [219, 879, 530, 182, 191],
       [184, 303, 424, 874, 147]])

9\. Select the values that are in the last 5 rows and the last 5 columns of `y`.

In [15]:
# Your answer here
y[-5:,-5:]

array([[610, 559, 982, 283, 128],
       [588, 856, 373, 435, 488],
       [357, 421, 157, 391, 970],
       [996, 498, 711, 665, 733],
       [739, 231, 968, 280, 946]])

10\. Select the value on the third row (i.e., row index position 2) and the fifth column (i.e., column index position 4) of `y`.

In [16]:
# Your answer here
y[2,4]

700

<hr>

In [17]:
np.random.seed(seed=0)
z = np.random.randint(-100, 101, 20)
z

array([ 72, -53,  17,  92, -33,  95,   3, -91, -79, -64, -13, -30, -12,
        40, -42,  93, -61, -13,  74, -12])

11\. Select all the negative values from `z`.

In [19]:
# Your answer here
z[z<0]

array([-53, -33, -91, -79, -64, -13, -30, -12, -42, -61, -13, -12])

12\. Select all the values from `z` that are greater than or equal to 50 or less than or equal to -50.

In [46]:
# Your answer here
z[(z>=50) | (z<=-50)]

array([ 72, -53,  92,  95, -91, -79, -64,  93, -61,  74])

<hr>

In [28]:
np.random.seed(seed=0)
data = np.random.randint(-100, 101, (5, 10))
data

array([[ 72, -53,  17,  92, -33,  95,   3, -91, -79, -64],
       [-13, -30, -12,  40, -42,  93, -61, -13,  74, -12],
       [-19,  65, -75, -23, -28, -91,  48,  15,  97, -21],
       [ 75,  92, -18,  -1,  77, -71,  47,  47,  42,  67],
       [-68,  93, -91,  85,  27, -68, -69,  51,  63,  14]])

In [29]:
labels = np.array(["c", "b", "c", "a", "b"])

13\. Suppose each label in `labels` corresponds to a row in `z`. Get all the rows from `data` that correspond to the labels *a* or *b*.

In [47]:
# Your answer here
data[(labels == "a") | (labels == "b")]

array([[-13, -30, -12,  40, -42,  93, -61, -13,  74, -12],
       [ 75,  92, -18,  -1,  77, -71,  47,  47,  42,  67],
       [-68,  93, -91,  85,  27, -68, -69,  51,  63,  14]])

14\. Set all the values in the corresponding rows to the label *c* in `data` to 0.

In [48]:
# Your answer here
data[(labels == "c")] = 0
data

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [-13, -30, -12,  40, -42,  93, -61, -13,  74, -12],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [ 75,  92, -18,  -1,  77, -71,  47,  47,  42,  67],
       [-68,  93, -91,  85,  27, -68, -69,  51,  63,  14]])

15\. Select the rows from `data` at the index positions 4, 0, and 2. (Order matters). 

In [50]:
# Your answer here
data[[4,0,2]]

array([[-68,  93, -91,  85,  27, -68, -69,  51,  63,  14],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0]])

## Exercises for Array Functions and Methods

1\. Create a 5 x 5 array `x` of integers from 1 to 25, such that the first row of `x` has integers from 1 to 5, the second row from 6 to 10, and so on and so forth. (Hint: use <b>reshape</b>.)

In [3]:
# Your answer here
x = np.arange(1, 26).reshape(5, 5)
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

2\. Get a copy of `x` collapsed into one dimension.

In [5]:
# Your answer here
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

3\. Get the min value in `x`.

In [6]:
# Your answer here
x.min()

1

4\. Get the index position of the max value in `x`.

In [7]:
# Your answer here
x.argmax()

24

5\. Negate `x` and save the result in `y`.

In [11]:
# Your answer here
y = -x
y

array([[ -1,  -2,  -3,  -4,  -5],
       [ -6,  -7,  -8,  -9, -10],
       [-11, -12, -13, -14, -15],
       [-16, -17, -18, -19, -20],
       [-21, -22, -23, -24, -25]])

6\. Calculate the element-wise addition of `x` and `y`.

In [9]:
# Your answer here
x+y

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

7\. Calculate the dot product of `x` and `y`.

In [10]:
# Your answer here
np.dot(x,y)

array([[ -215,  -230,  -245,  -260,  -275],
       [ -490,  -530,  -570,  -610,  -650],
       [ -765,  -830,  -895,  -960, -1025],
       [-1040, -1130, -1220, -1310, -1400],
       [-1315, -1430, -1545, -1660, -1775]])