# Introduction to Python
# Module 4 - Handling Numbers with NumPy

Instructor: Suyong Song 

Topics to be covered:
- NumPy Array Creation and Random Number Generation (+ exercises)
- Array Attributes and Methods
- Array Comparison
- Array Indexing and Slicing (+ exercises)
- Operations between Arrays and Scalars
- Fast Element-wise Array Functions and Array Methods (+ exercises)

NumPy, which stands for Numerical Python, is the fundamental package required for high performance scientific computing and data analysis.

## Import the NumPy Package

In [ ]:
# ! pip install --user --upgrade numpy

Note that you should install a package just once unless you need to upgrade it. Once it's installed, you can simply load it whenever you use it.  

In [1]:
import numpy as np

## Create NumPy Arrays from Python Lists

One of the key features of NumPy is its N-dimensional array object, or ndarray, which is a fast, flexible container for large data sets in Python.

In [2]:
x = np.array([1, 2, 3, 4, 5])
x

array([1, 2, 3, 4, 5])

numpy.array: https://numpy.org/doc/stable/reference/generated/numpy.array.html

You can create a NumPy ndarray from a primitive Python list using the <b>array</b> function. Now you can take advantage of all the useful features of NumPy that primitive Python lists do not offer. 

In [3]:
type(x)

numpy.ndarray

In [4]:
y = np.array([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [7.0, 8.0, 9.0]])
y

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

A nested list of equal-length lists will be converted into a multi-dimensional array.

In [5]:
type(y)

numpy.ndarray

## Other Ways to Create New Arrays

These NumPy functions are useful when you need to quickly generate an array of values that meets certain criteria. 

In [6]:
np.zeros(5)                    # a numpy array filled with 5 float zeros

array([0., 0., 0., 0., 0.])

numpy.zeros: https://numpy.org/doc/stable/reference/generated/numpy.zeros.html

The <b>zeros</b>(shape, dtype=float, ...) function returns a new array of given `shape` and `dtype`, filled with all zeros. The default data type is numpy.float64. 

In [7]:
np.zeros(5, dtype=int)         # a numpy array filled with 5 integer zeros

array([0, 0, 0, 0, 0])

In [8]:
np.zeros((5, 5), dtype=int)    # a 5 x 5 numpy array filled with all integer zeros

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

You can specify the shape of a two-dimensional array. 

In [9]:
np.ones((5, 5))                 # a 5 x 5 numpy array filled with all float ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

numpy.ones: https://numpy.org/doc/stable/reference/generated/numpy.ones.html

The <b>ones</b>(shape, dtype=None, ...) function returns a new array of given `shape` and `dtype`, filled with all ones. The default data type is numpy.float64.

In [10]:
np.ones((5, 5), dtype=int)       # a 5 x 5 numpy array filled with all integer ones

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [11]:
np.full((5, 5), 3.14)            # a 5 x 5 numpy array filled with all 3.14's

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

numpy.full: https://numpy.org/doc/stable/reference/generated/numpy.full.html

The <b>full</b>(shape, fill_value, dtype=None, ...) function returns a new array of given `shape` and `dtype`, filled with `fill_value`.

In [12]:
np.arange(0, 10)                 # a numpy array with integers from 0 to 9

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

numpy.arange: https://numpy.org/doc/stable/reference/generated/numpy.arange.html

The <b>arange</b>([start, ]stop, [step, ]dtype=None) function returns a new array of evenly spaced values within a given interval, which works almost the same as the built-in <b>range</b> function. Note that the parameter `start` is inclusive, while `stop` is exclusive. 

In [13]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

You can skip `start` if it is 0.

In [14]:
np.arange(0, 10, 2)               # a numpy array with integers from 0 to 9 stepping by 2

array([0, 2, 4, 6, 8])

The parameter `step` determines spacing between values.

In [15]:
np.linspace(0, 1, 5)              # a numpy array with 5 evenly spaced numbers from 0 and 1

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

numpy.linspace: https://numpy.org/doc/stable/reference/generated/numpy.linspace.html

The <b>linspace</b>(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0) function returns a new array of evenly spaced numbers over a specified interval. Note that both the `start` and `stop` parameters are inclusive. 

In [16]:
np.identity(5)                    # a 5 x 5 numpy identity array

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

numpy.identity: https://numpy.org/doc/stable/reference/generated/numpy.identity.html

The <b>identity</b>(n, dtype=None) function returns the identity array, which is a square array with 1's on the main diagonal and 0's elsewhere.

## Create Arrays of Random Numbers

The <b>numpy.random</b> module is used to efficiently generate arrays of sample values from commonly-used probability distributions.

In [17]:
np.random.normal(0, 1, 10)           # a numpy array of 10 random samples that follow a normal distribution 
                                     # with 0 being the mean and 1 being the standard deviation 

array([ 0.7437956 , -0.91929751, -0.31842226,  0.33018626, -0.25263959,
        0.89437388,  1.4360018 ,  0.95060166,  0.18020594,  1.6467959 ])

numpy.random.normal: https://numpy.org/doc/stable/reference/random/generated/numpy.random.normal.html

The <b>random.normal</b>(loc=0.0, scale=1.0, size=None) function returns a new array of random samples from a normal (Gaussian) distribution with `loc` being the mean and `scale` being the standard deviation of the distribution.

In [18]:
np.random.normal(0, 1, (2, 2))      # a 2 x 2 numpy array of a noral random variable

array([[0.3772804 , 0.13022934],
       [1.56161768, 1.3698237 ]])

In [19]:
np.random.uniform(0, 1, (3, 3))       # a 3 x 3 numpy array of random samples that follow a uniform distribution 
                                      # over the interval [0, 1) 

array([[0.64882438, 0.56377166, 0.53488516],
       [0.21591791, 0.22600113, 0.13931376],
       [0.33506792, 0.34715336, 0.72445288]])

numpy.random.uniform: https://numpy.org/doc/stable/reference/random/generated/numpy.random.uniform.html

The <b>random.uniform</b>(low=0.0, high=1.0, size=None) function returns a new array of random samples from a uniform distribution over the half-open interval [`low`, `high`) (`low` inclusive, but `high` exclusive). In other words, any value within the given interval is equally likely to be drawn by uniform.

There are other functions that return random samples from an other type of distribution such as <b>random.binomial</b> for the binomial distribution, <b>random.beta</b> for the beta distribution, <b>random.chisquare</b> for the chi-square distribution, and <b>random.gamma</b> for the gamma distribution. 

numpy.random.binomial: https://numpy.org/doc/stable/reference/random/generated/numpy.random.binomial.html<br>
numpy.random.beta: https://numpy.org/doc/stable/reference/random/generated/numpy.random.beta.html<br>
numpy.random.chisquare: https://numpy.org/doc/stable/reference/random/generated/numpy.random.chisquare.html<br>
numpy.random.gamma: https://numpy.org/doc/stable/reference/random/generated/numpy.random.gamma.html

In [20]:
np.random.randint(0, 10, (3, 3))     #  a 3 x 3 numpy array with random integers from 0 and 9

array([[8, 1, 8],
       [4, 1, 0],
       [4, 0, 9]])

numpy.random.randint: https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html

The <b>random.randint</b>(low, high=None, size=None, dtype='l') function returns a new array of random integers from `low` (inclusive) to `high` (exclusive).

In [21]:
np.random.choice(np.arange(10), 3, replace=False)     # choose 3 values from np.arage(10) with no duplicates 

array([8, 6, 2])

numpy.random.choice: https://numpy.org/doc/stable/reference/random/generated/numpy.random.choice.html

There are cases where you want to allow no duplicates in generated random numbers. The <b>random.choice</b>(a, size=None, replace=True, p=None) returns a new array of random samples from a given 1-D array. The first parameter `a` serves as a population, while the second parameter `size` serves as the sample size. When the third parameter `replace` is set to false, the sample has no replacement. 

In [22]:
np.random.permutation(10)

array([3, 6, 0, 5, 1, 7, 2, 8, 4, 9])

numpy.random.permutation: https://numpy.org/doc/stable/reference/random/generated/numpy.random.permutation.html

The <b>random.permutation</b>(x) function randomly permutes a sequence, or return a permuted range. If `x` is an integer, randomly permute np.arange(x).

In [23]:
np.random.permutation([1, 4, 9, 16, 25])

array([16,  9,  1,  4, 25])

If `x` is an array, make a copy and shuffle the values randomly.

In [24]:
np.random.seed(seed=0)   

numpy.random.seed: https://numpy.org/doc/stable/reference/random/generated/numpy.random.seed.html

The <b>random.seed</b>(seed=None) function seeds the generator. Random seeds are used for generating pseudo-random numbers, which are apparently random numbers but were generated based on seed values. The same random number generator and random seed always generates the same random numbers. This is useful for ensuring reproducibility.

In [25]:
np.random.seed(seed=0) 
np.random.randint(0, 10, (3, 3))

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2]])

You do not have to memorize the usage, especially the arguments, of each function. 

## Exercises for Arrays Creation

## Array Attributes

In [26]:
np.random.seed(seed=0) 
x = np.random.randint(0, 100, (3, 3))
x

array([[44, 47, 64],
       [67, 67,  9],
       [83, 21, 36]])

In [27]:
x.ndim 

2

The <b>ndim</b> attribute returns the number of dimensions of an array.

In [28]:
x.shape

(3, 3)

The <b>shape</b> attribute returns the shape of an array.

In [29]:
x.size

9

The <b>size</b> attribute returns the number of all values in an array.

In [30]:
x.dtype

dtype('int64')

The <b>dtype</b> attribute returns the data type of an array.

NumPy data types: https://numpy.org/doc/stable/user/basics.types.html

Note that the <b>ndim</b>, <b>shape</b>, <b>size</b>, and <b>dtype</b> are attributes, not methods, of NumPy arrays. There are no parentheses after them.

In [31]:
len(x)

3

The length of an array is the number of the first-dimension values.

## Array Comparisons

Comparison of arrays yields a Boolean array of element-wise answers.

In [32]:
x = np.array([1, 2, 3, 4, 5])
x

array([1, 2, 3, 4, 5])

In [33]:
x < 3

array([ True,  True, False, False, False])

In [34]:
x == 3

array([False, False,  True, False, False])

In [35]:
(x < 3) | (x == 3)        # or

array([ True,  True,  True, False, False])

In [36]:
(x < 3) & (x == 3)        # and

array([False, False, False, False, False])

## Array Indexing & Slicing

Indexing and slicing of NumPy arrays works basically the same as general indexing and slicing in Python, with some additional functionality such as Boolean indexing and Fancy Indexing. 

### 1-dimensional Arrays

In [37]:
np.random.seed(0)
x = np.random.randint(10, 100, 10)
x

array([54, 57, 74, 77, 77, 19, 93, 31, 46, 97])

In [38]:
x[0]

54

In [39]:
x[-1]

97

In [40]:
x[:3]

array([54, 57, 74])

In [41]:
x[:]

array([54, 57, 74, 77, 77, 19, 93, 31, 46, 97])

`x[:]` is equivalent to just `x`. 

In [42]:
x[::2]

array([54, 74, 77, 93, 46])

In [43]:
x[::-1] 

array([97, 46, 31, 93, 19, 77, 77, 74, 57, 54])

`x[::-1]` reverses `x`.

### 2-dimensional Arrays

In [44]:
np.random.seed(0)
x = np.random.randint(0, 100, (5, 5))
x

array([[44, 47, 64, 67, 67],
       [ 9, 83, 21, 36, 87],
       [70, 88, 88, 12, 58],
       [65, 39, 87, 46, 88],
       [81, 37, 25, 77, 72]])

Let's think of a 2D array as a matrix with rows and columns. 

In [45]:
x[0]     # Returns the first row of the matrix

array([44, 47, 64, 67, 67])

In [46]:
x[:3]    # Returns the first three rows of the matrix 

array([[44, 47, 64, 67, 67],
       [ 9, 83, 21, 36, 87],
       [70, 88, 88, 12, 58]])

`x[:n]` retrieves the first `n` rows.

In [47]:
x[0, 1]     # The first 0 refers to the first row, while the second 1 the second column

47

When retrieving a particular value in a 2D array, look up the row index first and then the column index, separated by a comma in matching square brackets.

In [48]:
x[:3, :3]   # The first :3 refers to the first 3 rows, while the second :3 the first three columns

array([[44, 47, 64],
       [ 9, 83, 21],
       [70, 88, 88]])

`x[:n, :n]` retrieves the values that are in the first `n` rows and `n` columns.

In [49]:
x[:, :3]    # The first : refers to all rows, while the second :3 the first three columns

array([[44, 47, 64],
       [ 9, 83, 21],
       [70, 88, 88],
       [65, 39, 87],
       [81, 37, 25]])

`x[:, :n]` retrieves the first `n` columns.

### Boolean indexing

In [50]:
np.random.seed(0)
data = np.random.normal(75, 10, (7, 3))
data

array([[92.64052346, 79.00157208, 84.78737984],
       [97.40893199, 93.6755799 , 65.2272212 ],
       [84.50088418, 73.48642792, 73.96781148],
       [79.10598502, 76.44043571, 89.54273507],
       [82.61037725, 76.21675016, 79.43863233],
       [78.33674327, 89.94079073, 72.94841736],
       [78.13067702, 66.45904261, 49.47010184]])

In [51]:
data > 90

array([[ True, False, False],
       [ True,  True, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

Comparing `data` with a number 90 yields a Boolean array of element-wise answers.

In [52]:
data[data > 90]     # Returns all the values in data that are greater than 90.

array([92.64052346, 97.40893199, 93.6755799 ])

This Boolean array, which is called a mask, can be passed when indexing the array. This is called Bollean indexing. The Boolean array must be of the same length as the axis it is indexing. Boolean indexing returns an array of the values that correspond to True. 

In [53]:
l = list(data)
l[l > 90]

TypeError: '>' not supported between instances of 'list' and 'int'

Note that primitive Python lists do not support this kind of Boolean indexing. 

In [54]:
names = np.array(['Bob', 'Alice', 'Sam', 'Bob', 'Sam', 'Alice', 'Alice'])
names

array(['Bob', 'Alice', 'Sam', 'Bob', 'Sam', 'Alice', 'Alice'], dtype='<U5')

Suppose each name in `names` corresponds to a row in `data`.

In [55]:
names == "Bob"

array([ True, False, False,  True, False, False, False])

Comparing `names` with a string *Bob* yields a Boolean array of element-wise answers.

In [56]:
data[names == "Bob"]    # Returns all the values in data that correspond to Bob.

array([[92.64052346, 79.00157208, 84.78737984],
       [79.10598502, 76.44043571, 89.54273507]])

This Boolean array can be passed as a mask when indexing the array.

In [57]:
data[names == "Alice"]   # Returns all the values in data that correspond to Alice.

array([[97.40893199, 93.6755799 , 65.2272212 ],
       [78.33674327, 89.94079073, 72.94841736],
       [78.13067702, 66.45904261, 49.47010184]])

In [58]:
data[names != "Alice"]   # Returns all the values in data that do not correspond to Alice.

array([[92.64052346, 79.00157208, 84.78737984],
       [84.50088418, 73.48642792, 73.96781148],
       [79.10598502, 76.44043571, 89.54273507],
       [82.61037725, 76.21675016, 79.43863233]])

In [59]:
data[~(names == "Alice")]

array([[92.64052346, 79.00157208, 84.78737984],
       [84.50088418, 73.48642792, 73.96781148],
       [79.10598502, 76.44043571, 89.54273507],
       [82.61037725, 76.21675016, 79.43863233]])

The <b>~</b> operator negates the whole Boolean array. 

In [60]:
mask = (names == 'Bob') | (names == 'Alice')
mask

array([ True,  True, False,  True, False,  True,  True])

To select two of the three names, use Boolean arithmetic operators like & (i.e., and) and | (i.e., or) and assign the resulting Boolean array to a variable, say `mask`. 

In [61]:
data[mask]

array([[92.64052346, 79.00157208, 84.78737984],
       [97.40893199, 93.6755799 , 65.2272212 ],
       [79.10598502, 76.44043571, 89.54273507],
       [78.33674327, 89.94079073, 72.94841736],
       [78.13067702, 66.45904261, 49.47010184]])

Then you can pass `mask` for indexing `data`.

Note that selecting data from an array by Boolean indexing always returns a copy of the target array, not changing its content.

In [62]:
data[data < 80] = 0     # Sets all of the values less than 80 to 0.
data

array([[92.64052346,  0.        , 84.78737984],
       [97.40893199, 93.6755799 ,  0.        ],
       [84.50088418,  0.        ,  0.        ],
       [ 0.        ,  0.        , 89.54273507],
       [82.61037725,  0.        ,  0.        ],
       [ 0.        , 89.94079073,  0.        ],
       [ 0.        ,  0.        ,  0.        ]])

You can set values with boolean arrays. Only the values that correspond to True are affected. 

In [63]:
data[names == "Sam"] = 100
data

array([[ 92.64052346,   0.        ,  84.78737984],
       [ 97.40893199,  93.6755799 ,   0.        ],
       [100.        , 100.        , 100.        ],
       [  0.        ,   0.        ,  89.54273507],
       [100.        , 100.        , 100.        ],
       [  0.        ,  89.94079073,   0.        ],
       [  0.        ,   0.        ,   0.        ]])

This way, you can set the whole rows or columns.

### Fancy Indexing

Fancy Indexing is a term coined by NumPy to describe indexing using integer arrays.

In [64]:
x = np.array([num * 10 for num in np.arange(10)])
x

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [65]:
mask = [0, 7, 1]
x[mask]

array([ 0, 70, 10])

To select out a subset of the rows in a particular order, you can simply pass a list or array of integers, or index positions, specifying the desired order.

In [66]:
mask = [-1, -5, -3]
x[mask]

array([90, 50, 70])

You can alsway use negative index positions. 

## Exercises for Array Indexing and Slicing

## Operations between Arrays and Scalars

NumPy arrays allows you to express batch operations on data without writing any <b>for</b> loops. This is usually called vectorization. Any arithmetic operations between equal-size arrays applies the operation elementwise.

In [67]:
x = np.array([1, 2, 3, 4, 5])
x

array([1, 2, 3, 4, 5])

In [68]:
x + 1                   # a new numpy array with each value in x added by 1

array([2, 3, 4, 5, 6])

This is called element-wise addition.

In [69]:
l = [1, 2, 3, 4, 5]
l + 1

TypeError: can only concatenate list (not "int") to list

Note that primitive Python lists do not support this element-wise operation.

In [70]:
[num + 1 for num in l]

[2, 3, 4, 5, 6]

You need a <b>for</b> loop or list comprehension to do the same thing with a primitive Python list.

In [71]:
x - 1

array([0, 1, 2, 3, 4])

In [72]:
x * 2

array([ 2,  4,  6,  8, 10])

In [73]:
x / 2

array([0.5, 1. , 1.5, 2. , 2.5])

In [74]:
1 / x

array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ])

In [75]:
x ** 2

array([ 1,  4,  9, 16, 25])

In [76]:
-x

array([-1, -2, -3, -4, -5])

In [77]:
x = np.array([1, 2, 3])
y = np.array([1, 3, 5])

In [78]:
x + y

array([2, 5, 8])

In [79]:
x * y

array([ 1,  6, 15])

In [80]:
x = np.array([1, 2, 3, 4, 5])
y = np.array([1, 3, 5])
x + y

ValueError: operands could not be broadcast together with shapes (5,) (3,) 

The two operands must have the same shape for addition, subtraction, muliplication, and division. 

## Fast Element-wise Array Functions

Mathematical functions: https://numpy.org/doc/stable/reference/routines.math.html

In [81]:
x = np.array([-1, 2, -3, 4, -5])
np.absolute(x)      # absolute values

array([1, 2, 3, 4, 5])

numpy.absolute: https://numpy.org/doc/stable/reference/generated/numpy.absolute.html

In [82]:
x = np.array([1, 2, 3])
np.exp(x)            # exponential (= e^x)

array([ 2.71828183,  7.3890561 , 20.08553692])

numpy.exp: https://numpy.org/doc/stable/reference/generated/numpy.exp.html

In [83]:
x = np.array([1, 2, 3])
np.power(3, x)        # power (= 3^x)

array([ 3,  9, 27])

In [84]:
x = np.array([1, 2, 3])
np.power(x, 3)        # power (= x^3)

array([ 1,  8, 27])

numpy.power: https://numpy.org/doc/stable/reference/generated/numpy.power.html

In [85]:
x = [1, 2, 4, 8]
np.log(x)             # ln(x)

array([0.        , 0.69314718, 1.38629436, 2.07944154])

numpy.log: https://numpy.org/doc/stable/reference/generated/numpy.log.html

In [86]:
x = [1, 2, 4, 8]
np.log2(x)            # log2(x): Base-2 logarithm of x

array([0., 1., 2., 3.])

numpy.log2: https://numpy.org/doc/stable/reference/generated/numpy.log2.html

In [87]:
x = [1, 2, 4, 8]
np.log10(x)           # log10(x)

array([0.        , 0.30103   , 0.60205999, 0.90308999])

numpy.log10: https://numpy.org/doc/stable/reference/generated/numpy.log10.html

In [88]:
x = np.array([[1, 2], [3, 4]])
x

array([[1, 2],
       [3, 4]])

In [89]:
y = np.array([[5, 6], [7, 8]])
y

array([[5, 6],
       [7, 8]])

In [90]:
np.dot(x, y)          # dot product of two arrays

array([[19, 22],
       [43, 50]])

numpy.dot: https://numpy.org/doc/stable/reference/generated/numpy.dot.html

In [91]:
np.multiply(x, y)     # multiply arguments element-wise

array([[ 5, 12],
       [21, 32]])

In [92]:
x*y                   # The * operator can be used as a shorthand for np.multiply

array([[ 5, 12],
       [21, 32]])

## Array Methods

In [93]:
np.random.seed(0)
x = np.random.randint(0, 50, 10)
x

array([44, 47,  0,  3,  3, 39,  9, 19, 21, 36])

In [94]:
x.sum()              # equivalent to np.sum(x)

221

numpy.ndarray.sum: https://numpy.org/doc/stable/reference/generated/numpy.ndarray.sum.html

In [95]:
x.cumsum()

array([ 44,  91,  91,  94,  97, 136, 145, 164, 185, 221])

numpy.ndarray.cumsum: https://numpy.org/doc/stable/reference/generated/numpy.ndarray.cumsum.html

The <b>cumsum</b>(axis=None, dtype=None, out=None) returns the cumulative sum of the values along the given `axis`.

In [96]:
x.prod()

0

numpy.ndarray.prod: https://numpy.org/doc/stable/reference/generated/numpy.ndarray.prod.html

In [97]:
x.cumprod()

array([  44, 2068,    0,    0,    0,    0,    0,    0,    0,    0])

numpy.ndarray.cumprod: https://numpy.org/doc/stable/reference/generated/numpy.ndarray.cumprod.html

The <b>cumprod</b>(axis=None, dtype=None, out=None) returns the cumulative product of the values along the given `axis`.

In [98]:
x.mean()

22.1

numpy.ndarray.mean: https://numpy.org/doc/stable/reference/generated/numpy.ndarray.mean.html

In [99]:
x.var()

297.89000000000004

numpy.ndarray.var: https://numpy.org/doc/stable/reference/generated/numpy.ndarray.var.html

In [100]:
x.std()

17.259490143106778

numpy.ndarray.std: https://numpy.org/doc/stable/reference/generated/numpy.ndarray.std.html

In [101]:
x.min() 

0

numpy.ndarray.min: https://numpy.org/doc/stable/reference/generated/numpy.ndarray.min.html

In [102]:
x.max()

47

numpy.ndarray.max: https://numpy.org/doc/stable/reference/generated/numpy.ndarray.max.html

In [103]:
x.argmin()

2

numpy.ndarray.argmin: https://numpy.org/doc/stable/reference/generated/numpy.ndarray.argmin.html

The <b>argmin</b>(axis=None, out=None) returns indices of the minimum values along the given `axis` of a.

In [104]:
x.argmax()

1

numpy.ndarray.argmax: https://numpy.org/doc/stable/reference/generated/numpy.ndarray.argmax.html

The <b>argmax</b>(axis=None, out=None) returns indices of the maximum values along the given `axis`.

In [105]:
x = np.arange(15)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [106]:
y = x.reshape((3, 5))
y

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

numpy.ndarray.reshape: https://numpy.org/doc/stable/reference/generated/numpy.ndarray.reshape.html

The <b>reshape</b>(shape, ...) method returns an array containing the same data with a new `shape`.

In [107]:
y.transpose()

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

numpy.ndarray.transpose: https://numpy.org/doc/stable/reference/generated/numpy.ndarray.transpose.html

The <b>transpose</b>(*axes) returns a view of the array with `axes` transposed.

In [108]:
y.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

numpy.ndarray.flatten: https://numpy.org/doc/stable/reference/generated/numpy.ndarray.flatten.html

The <b>flatten</b> method returns a copy of the array collapsed into one dimension. <b>flatten</b> is the opposite of <b>reshape</b>.

In [109]:
x.astype(float)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14.])

numpy.ndarray.astype: https://numpy.org/doc/stable/reference/generated/numpy.ndarray.astype.html

The <b>astype</b>(dtype, ...) copies of the array, cast to a specified `dtype`.

## Exercises for Array Functions and Methods